// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6RzzhrugCMN9kyOUlRAP4RgacGM1scXU',
    appId: '1:1010563950783:web:1373321314af7a341a3e0a',
    messagingSenderId: '1010563950783',
    projectId: 'food-calories-scanner',
    authDomain: 'food-calories-scanner.firebaseapp.com',
    storageBucket: 'food-calories-scanner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2VnJUugGpckklZSYX0jQYfO79JuB_eGI',
    appId: '1:1010563950783:android:f016bfe5ff86f19d1a3e0a',
    messagingSenderId: '1010563950783',
    projectId: 'food-calories-scanner',
    storageBucket: 'food-calories-scanner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY6EWYYocc2k0X0vxfWlYCCGc0IT-4se4',
    appId: '1:1010563950783:ios:28feed4587cfc5491a3e0a',
    messagingSenderId: '1010563950783',
    projectId: 'food-calories-scanner',
    storageBucket: 'food-calories-scanner.firebasestorage.app',
    iosBundleId: 'com.example.foodScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY6EWYYocc2k0X0vxfWlYCCGc0IT-4se4',
    appId: '1:1010563950783:ios:28feed4587cfc5491a3e0a',
    messagingSenderId: '1010563950783',
    projectId: 'food-calories-scanner',
    storageBucket: 'food-calories-scanner.firebasestorage.app',
    iosBundleId: 'com.example.foodScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6RzzhrugCMN9kyOUlRAP4RgacGM1scXU',
    appId: '1:1010563950783:web:fb3684df3f4c268c1a3e0a',
    messagingSenderId: '1010563950783',
    projectId: 'food-calories-scanner',
    authDomain: 'food-calories-scanner.firebaseapp.com',
    storageBucket: 'food-calories-scanner.firebasestorage.app',
  );
}
